{% set name = "ptitprince" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptitprince-{{ version }}.tar.gz
  sha256: 0966e0b585b18d2c1975f526f6fa87ab3c8543ccd76da67c74f542e0d97d19ac

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python
    - cython
    - matplotlib-base
    - numpy >=1.16
    - pyhamcrest >=1.9.0
    - scipy
    - seaborn ==0.11
    - pandas >=1.0

test:
  imports:
    - ptitprince
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pog87/PtitPrince
  summary: A Python implementation of Rainclouds, originally on R, ggplot2. Written on top of seaborn.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pog87
    - sappelhoff
