{% set name = "ptitprince" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptitprince-{{ version }}.tar.gz
  sha256: bbd19d4f8615935ac1b750651907303913fbdddc3fe864c1cb80faa3a2a3acfb

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}
    - pip    
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base <3.9
    - numpy >=1.16
    - scipy >=1.0
    - seaborn ==0.11

test:
  imports:
    - ptitprince
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/pog87/PtitPrince
  summary: A Python implementation of Rainclouds, originally on R, ggplot2. Written on top of seaborn.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pog87
    - sappelhoff
