{% set name = "ptitprince" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptitprince-{{ version }}.tar.gz
  sha256: bbd19d4f8615935ac1b750651907303913fbdddc3fe864c1cb80faa3a2a3acfb

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python
    - cython
    - matplotlib-base
    - numpy >=1.16
    - pyhamcrest >=1.9.0
    - scipy
    - seaborn ==0.11
    - pandas >=1.0

test:
  imports:
    - ptitprince
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pog87/PtitPrince
  summary: A Python implementation of Rainclouds, originally on R, ggplot2. Written on top of seaborn.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pog87
    - sappelhoff
